
export const API_SIGNIN = 'http://peargameapi.herokuapp.com/api/signin'
export const API_USERS = 'http://peargameapi.herokuapp.com/api/users/'
export const API_GETUSER = 'http://peargameapi.herokuapp.com/api/users/:iduser'
export const API_UPDATE_KILLS = 'http://peargameapi.herokuapp.com/api/update_kills'
export const API_UPDATE_COINS = 'http://peargameapi.herokuapp.com/api/update_coins'
export const API_UPDATE_USERNAME = 'http://peargameapi.herokuapp.com/api/update_username'
export const API_UPDATE_EMAIL = 'http://peargameapi.herokuapp.com/api/update_email'
export const API_UPDATE_PASSWORD = 'http://peargameapi.herokuapp.com/api/update_password'
export const API_WEAPON = 'http://peargameapi.herokuapp.com/api/update_weapon'
export const API_SHIELD = 'http://peargameapi.herokuapp.com/api/update_shield'
export const API_HEAD = 'http://peargameapi.herokuapp.com/api/update_head'
export const API_CHEST = 'http://peargameapi.herokuapp.com/api/update_chest'
export const API_LEGS = 'http://peargameapi.herokuapp.com/api/update_legs'
export const API_FEET = 'http://peargameapi.herokuapp.com/api/update_feet'
